import { stemFileBase } from './naming.js';

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');

const STYLE = `body{font:12px/1.5 system-ui,sans-serif;color:#1c1e2a;margin:28px}
h1{font-size:16px;font-weight:600;margin:0 0 14px}h2{font-size:13px;font-weight:600;margin:20px 0 8px}
table{border-collapse:collapse;width:100%}
th,td{border:1px solid #c8ccd8;padding:5px 8px;text-align:left;font-size:11px;vertical-align:top}
th{background:#eef0f6}td small,p small{color:#666}@media print{body{margin:8mm}}`;

const SETUP_NOTE = `Trigs, slice p-locks and per-track scales (master length INF, master scale 1x) are
pre-programmed into the bank files. The per-track scale is set only on the tracks listed above; any
other track — one you keep for remixing, and the master track 8 — keeps the scale it already had.
Trigs carry no sample locks — each track plays its default sample.
One-time device step: on each used track in the part, assign a STATIC machine and set its default sample
(TRK DEFAULT) to the slot in the table above. If a track shows no slices, reload the slot&#39;s sample once —
the .ot file beside each WAV carries the slice grid. The table below is a reference (and the manual recipe
for any bank that failed verification).`;

/** Printable map of what every pattern trigs — also the manual fallback. */
export function patternSheetHtml({ stems, tracks, regions, bpm, abbrev, withSetup }) {
  const title = `${esc(abbrev || 'OSSC')} — Octatrack pattern map · ${bpm} BPM`;
  let h = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>`
    + `<style>${STYLE}</style></head><body><h1>${title}</h1>`;

  if (withSetup) {
    h += '<h2>Static sample slots (written into project.work)</h2>'
      + '<table><tr><th>Slot</th><th>Track</th><th>File</th><th>Slices</th></tr>';
    stems.forEach((stem, i) => {
      const track = tracks.get(stem.id);
      if (!track || !track.slices.length) return;
      h += `<tr><td>${i + 1}</td><td>T${i + 1} ${esc(stem.name)}</td>`
        + `<td>${esc(stemFileBase(stem, i, abbrev))}.wav</td><td>${Math.min(64, track.slices.length)}</td></tr>`;
    });
    h += `</table><p><small>${SETUP_NOTE}</small></p>`
      + '<h2>Patterns (Bank 2 onward — Bank 1 untouched)</h2>';
  }

  h += '<table><tr><th></th>';
  for (const r of regions) {
    h += `<th>${esc(String(r.idx).padStart(2, '0') + ' ' + (r.name || ''))}`
      + `<small>${esc(`${r.bp} · ${r.len} bars · ${r.scale.label} · ${r.scale.master}`)}</small></th>`;
  }
  h += '</tr>';

  for (const stem of stems) {
    const track = tracks.get(stem.id);
    if (!track) continue;
    h += `<tr><th>${esc(stem.name)}</th>`;
    for (const r of regions) {
      const slice = track.slices.find(s => s.region.idx === r.idx);
      const detail = slice && slice.trig !== 1
        ? `<small style="display:block">song bar ${slice.aM + 1} = pattern bar ${slice.aM - r.start + 1} · trig step ${slice.trig}</small>`
        : '';
      h += `<td>${slice ? `Slice ${slice.num}${detail}` : '—'}</td>`;
    }
    h += '</tr>';
  }

  return h + '</table><p style="color:#666;font-size:10px;margin-top:12px">'
    + 'Generated by OSSC — patterns start at Bank 2; Bank 1 reserved for your intro.</p></body></html>';
}

/** Same information as rows for a spreadsheet. */
export function patternCsvRows({ stems, tracks, regions }) {
  const rows = [
    ['', ...regions.map(r => String(r.idx).padStart(2, '0') + (r.name ? ' ' + r.name : ''))],
    ['Pattern', ...regions.map(r => r.bp)],
    ['Length (bars)', ...regions.map(r => r.len)],
    ['Scale', ...regions.map(r => r.scale.label)],
    ['Master', ...regions.map(r => r.scale.master)],
  ];
  for (const stem of stems) {
    const track = tracks.get(stem.id);
    rows.push([stem.name, ...regions.map(r => {
      const slice = track && track.slices.find(s => s.region.idx === r.idx);
      if (!slice) return '';
      const detail = slice.trig !== 1
        ? ` · song bar ${slice.aM + 1} = pattern bar ${slice.aM - r.start + 1} · trig step ${slice.trig}`
        : '';
      return `Slice ${slice.num}${detail}`;
    })]);
  }
  return rows;
}
